### ISSUE TITLE
NPE when exporting pipeline

### ISSUE THREAD

**Issue by ketan** [gocd-contrib/gocd-groovy-dsl-config-plugin#58]
```
2019-03-26T04:18:30.177690445Z java.lang.RuntimeException: java.lang.NullPointerException
2019-03-26T04:18:30.177698870Z 	at cd.go.contrib.plugins.configrepo.groovy.executors.PipelineExportExecutor.exportedSource(PipelineExportExecutor.java:86)
2019-03-26T04:18:30.177702215Z 	at cd.go.contrib.plugins.configrepo.groovy.executors.PipelineExportExecutor.execute(PipelineExportExecutor.java:43)
2019-03-26T04:18:30.177704923Z 	at cd.go.contrib.plugins.configrepo.groovy.GroovyDslPlugin.handle(GroovyDslPlugin.java:58)
2019-03-26T04:18:30.177707563Z 	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:148)
2019-03-26T04:18:30.177710094Z 	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:286)
2019-03-26T04:18:30.177713003Z 	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:228)
2019-03-26T04:18:30.177715608Z 	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:145)
2019-03-26T04:18:30.177718225Z 	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
2019-03-26T04:18:30.177721659Z 	at com.thoughtworks.go.plugin.access.configrepo.ConfigRepoExtension.pipelineExport(ConfigRepoExtension.java:70)
2019-03-26T04:18:30.177725735Z 	at com.thoughtworks.go.config.ConfigRepoPlugin.pipelineExport(ConfigRepoPlugin.java:73)
2019-03-26T04:18:30.177729182Z 	at com.thoughtworks.go.apiv1.export.ExportControllerV1.exportPipeline(ExportControllerV1.java:101)
2019-03-26T04:18:30.177732858Z 	at spark.RouteImpl$1.handle(RouteImpl.java:72)
2019-03-26T04:18:30.177736084Z 	at spark.http.matching.Routes.execute(Routes.java:61)
2019-03-26T04:18:30.177738949Z 	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
2019-03-26T04:18:30.177741514Z 	at spark.servlet.SparkFilter.doFilter(SparkFilter.java:173)
2019-03-26T04:18:30.177743937Z 	at com.thoughtworks.go.spark.SparkPreFilter.doFilter(SparkPreFilter.java:53)
2019-03-26T04:18:30.177746548Z 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
2019-03-26T04:18:30.177749154Z 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
2019-03-26T04:18:30.177753052Z 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
2019-03-26T04:18:30.177757485Z 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:614)
2019-03-26T04:18:30.177761573Z 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
2019-03-26T04:18:30.177765162Z 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
2019-03-26T04:18:30.177767715Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
2019-03-26T04:18:30.177770326Z 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
2019-03-26T04:18:30.177772797Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
2019-03-26T04:18:30.177777713Z 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
2019-03-26T04:18:30.177780949Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
2019-03-26T04:18:30.177784638Z 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
2019-03-26T04:18:30.177788392Z 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
2019-03-26T04:18:30.177790960Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
2019-03-26T04:18:30.177798162Z 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
2019-03-26T04:18:30.177814676Z 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
2019-03-26T04:18:30.177820416Z 	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:227)
2019-03-26T04:18:30.177824128Z 	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:78)
2019-03-26T04:18:30.177841116Z 	at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:213)
2019-03-26T04:18:30.177845437Z 	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)
2019-03-26T04:18:30.177849474Z 	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
2019-03-26T04:18:30.177853545Z 	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
2019-03-26T04:18:30.177857113Z 	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:381)
2019-03-26T04:18:30.177861025Z 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
2019-03-26T04:18:30.177865178Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
2019-03-26T04:18:30.177869206Z 	at com.thoughtworks.go.server.web.FlashLoadingFilter.doFilterInternal(FlashLoadingFilter.java:39)
2019-03-26T04:18:30.177873899Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2019-03-26T04:18:30.177877954Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.177882014Z 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
2019-03-26T04:18:30.177885814Z 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
2019-03-26T04:18:30.177889633Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.177893707Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
2019-03-26T04:18:30.177897854Z 	at com.thoughtworks.go.server.newsecurity.filters.DenyIfRefererIsNotFilesFilter.doFilterInternal(DenyIfRefererIsNotFilesFilter.java:53)
2019-03-26T04:18:30.177906397Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2019-03-26T04:18:30.177910545Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.177916098Z 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
2019-03-26T04:18:30.177920029Z 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
2019-03-26T04:18:30.177923857Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.177927973Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
2019-03-26T04:18:30.177932018Z 	at com.thoughtworks.go.server.newsecurity.filters.VerifyAuthorityFilter.doFilterInternal(VerifyAuthorityFilter.java:58)
2019-03-26T04:18:30.177935770Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2019-03-26T04:18:30.177939803Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.177943794Z 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
2019-03-26T04:18:30.177947852Z 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
2019-03-26T04:18:30.177951709Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.177955734Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
2019-03-26T04:18:30.177960389Z 	at com.thoughtworks.go.server.newsecurity.filters.AbstractUserEnabledCheckFilter.doFilterInternal(AbstractUserEnabledCheckFilter.java:67)
2019-03-26T04:18:30.177964877Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2019-03-26T04:18:30.177968906Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.177972756Z 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
2019-03-26T04:18:30.177976413Z 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
2019-03-26T04:18:30.177980399Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.177984305Z 	at com.thoughtworks.go.server.newsecurity.filters.ThreadLocalUserFilter.doFilterInternal(ThreadLocalUserFilter.java:42)
2019-03-26T04:18:30.177988272Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2019-03-26T04:18:30.177992263Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.177996100Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
2019-03-26T04:18:30.178023127Z 	at com.thoughtworks.go.server.newsecurity.filters.AccessTokenAuthenticationFilter.filterWhenSecurityEnabled(AccessTokenAuthenticationFilter.java:124)
2019-03-26T04:18:30.178032879Z 	at com.thoughtworks.go.server.newsecurity.filters.AccessTokenAuthenticationFilter.doFilterInternal(AccessTokenAuthenticationFilter.java:87)
2019-03-26T04:18:30.178037138Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2019-03-26T04:18:30.178040796Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.178044620Z 	at com.thoughtworks.go.server.newsecurity.filters.AbstractBasicAuthenticationFilter.filterWhenSecurityEnabled(AbstractBasicAuthenticationFilter.java:89)
2019-03-26T04:18:30.178048559Z 	at com.thoughtworks.go.server.newsecurity.filters.AbstractBasicAuthenticationFilter.doFilterInternal(AbstractBasicAuthenticationFilter.java:68)
2019-03-26T04:18:30.178052418Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2019-03-26T04:18:30.178055911Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.178061368Z 	at com.thoughtworks.go.server.newsecurity.filters.AssumeAnonymousUserFilter.doFilterInternal(AssumeAnonymousUserFilter.java:65)
2019-03-26T04:18:30.178064978Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2019-03-26T04:18:30.178068551Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.178080105Z 	at com.thoughtworks.go.server.newsecurity.filters.AbstractReAuthenticationFilter.doFilterInternal(AbstractReAuthenticationFilter.java:75)
2019-03-26T04:18:30.178084714Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2019-03-26T04:18:30.178088372Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.178091989Z 	at com.thoughtworks.go.server.newsecurity.filters.InvalidateAuthenticationOnSecurityConfigChangeFilter.doFilterInternal(InvalidateAuthenticationOnSecurityConfigChangeFilter.java:106)
2019-03-26T04:18:30.178096005Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2019-03-26T04:18:30.178099481Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.178102976Z 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
2019-03-26T04:18:30.178106497Z 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
2019-03-26T04:18:30.178109890Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.178113417Z 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
2019-03-26T04:18:30.178120037Z 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
2019-03-26T04:18:30.178123601Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.178127238Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
2019-03-26T04:18:30.178130882Z 	at com.thoughtworks.go.server.newsecurity.filters.AlwaysCreateSessionFilter.doFilterInternal(AlwaysCreateSessionFilter.java:41)
2019-03-26T04:18:30.178134545Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2019-03-26T04:18:30.178138573Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.178142245Z 	at com.thoughtworks.go.server.newsecurity.filters.AbstractSessionReduceIdleTimeoutFilter.doFilterInternal(AbstractSessionReduceIdleTimeoutFilter.java:45)
2019-03-26T04:18:30.178146013Z 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
2019-03-26T04:18:30.178149449Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.178153170Z 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
2019-03-26T04:18:30.178156820Z 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
2019-03-26T04:18:30.178160424Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.178164004Z 	at com.thoughtworks.go.server.newsecurity.filters.ModeAwareFilter.doFilter(ModeAwareFilter.java:81)
2019-03-26T04:18:30.178167571Z 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
2019-03-26T04:18:30.178171112Z 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
2019-03-26T04:18:30.178174510Z 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
2019-03-26T04:18:30.178177924Z 	at com.thoughtworks.go.server.newsecurity.filterchains.MainFilterChain.doFilter(MainFilterChain.java:77)
2019-03-26T04:18:30.178181592Z 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
2019-03-26T04:18:30.178192797Z 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
2019-03-26T04:18:30.178196697Z 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
2019-03-26T04:18:30.178200225Z 	at com.thoughtworks.go.server.web.BackupFilter.doFilter(BackupFilter.java:88)
2019-03-26T04:18:30.178203891Z 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
2019-03-26T04:18:30.178206929Z 	at com.thoughtworks.go.server.web.DefaultHeadersFilter.doFilter(DefaultHeadersFilter.java:50)
2019-03-26T04:18:30.178210504Z 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
2019-03-26T04:18:30.178216864Z 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
2019-03-26T04:18:30.178220501Z 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
2019-03-26T04:18:30.178224175Z 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
2019-03-26T04:18:30.178227814Z 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
2019-03-26T04:18:30.178231304Z 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
2019-03-26T04:18:30.178234756Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
2019-03-26T04:18:30.178238270Z 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
2019-03-26T04:18:30.178241826Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
2019-03-26T04:18:30.178245448Z 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
2019-03-26T04:18:30.178249169Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
2019-03-26T04:18:30.178252763Z 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
2019-03-26T04:18:30.178256208Z 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
2019-03-26T04:18:30.178267037Z 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
2019-03-26T04:18:30.178270596Z 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
2019-03-26T04:18:30.178274020Z 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
2019-03-26T04:18:30.178277604Z 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
2019-03-26T04:18:30.178281128Z 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
2019-03-26T04:18:30.178284772Z 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
2019-03-26T04:18:30.178288284Z 	at org.eclipse.jetty.server.Server.handle(Server.java:502)
2019-03-26T04:18:30.178291772Z 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
2019-03-26T04:18:30.178295150Z 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
2019-03-26T04:18:30.178298760Z 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
2019-03-26T04:18:30.178302262Z 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
2019-03-26T04:18:30.178305686Z 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
2019-03-26T04:18:30.178314836Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
2019-03-26T04:18:30.178321421Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
2019-03-26T04:18:30.178326616Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
2019-03-26T04:18:30.178330325Z 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
2019-03-26T04:18:30.178333927Z 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
2019-03-26T04:18:30.178337664Z 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
2019-03-26T04:18:30.178341286Z 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
2019-03-26T04:18:30.178344914Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-26T04:18:30.178348359Z Caused by: java.lang.NullPointerException: null
2019-03-26T04:18:30.178351575Z 	at cd.go.contrib.plugins.configrepo.groovy.export.IndentedStringWriter.quoteValue(IndentedStringWriter.java:121)
2019-03-26T04:18:30.178355310Z 	at cd.go.contrib.plugins.configrepo.groovy.export.IndentedStringWriter.lambda$null$0(IndentedStringWriter.java:100)
2019-03-26T04:18:30.178359064Z 	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
2019-03-26T04:18:30.178362534Z 	at cd.go.contrib.plugins.configrepo.groovy.export.IndentedStringWriter.lambda$property$2(IndentedStringWriter.java:98)
2019-03-26T04:18:30.178366286Z 	at cd.go.contrib.plugins.configrepo.groovy.export.IndentedStringWriter.withIndent(IndentedStringWriter.java:127)
2019-03-26T04:18:30.178370024Z 	at cd.go.contrib.plugins.configrepo.groovy.export.IndentedStringWriter.property(IndentedStringWriter.java:95)
2019-03-26T04:18:30.178373552Z 	at cd.go.contrib.plugins.configrepo.groovy.export.GroovyExporter.exportSimplePropertiesOf(GroovyExporter.java:145)
2019-03-26T04:18:30.178377216Z 	at cd.go.contrib.plugins.configrepo.groovy.export.GroovyExporter.exportPropertiesOf(GroovyExporter.java:79)
2019-03-26T04:18:30.178380904Z 	at cd.go.contrib.plugins.configrepo.groovy.export.GroovyExporter.lambda$export$2(GroovyExporter.java:68)
2019-03-26T04:18:30.178384640Z 	at cd.go.contrib.plugins.configrepo.groovy.export.IndentedStringWriter.withIndent(IndentedStringWriter.java:127)
2019-03-26T04:18:30.178388365Z 	at cd.go.contrib.plugins.configrepo.groovy.export.IndentedStringWriter.newEntity(IndentedStringWriter.java:51)
2019-03-26T04:18:30.178392106Z 	at cd.go.contrib.plugins.configrepo.groovy.export.GroovyExporter.export(GroovyExporter.java:67)
2019-03-26T04:18:30.178395816Z 	at cd.go.contrib.plugins.configrepo.groovy.export.GroovyExporter.lambda$null$0(GroovyExporter.java:52)
2019-03-26T04:18:30.178399536Z 	at cd.go.contrib.plugins.configrepo.groovy.export.IndentedStringWriter.withIndent(IndentedStringWriter.java:127)
2019-03-26T04:18:30.178403826Z 	at cd.go.contrib.plugins.configrepo.groovy.export.IndentedStringWriter.newEntity(IndentedStringWriter.java:51)
2019-03-26T04:18:30.178407469Z 	at cd.go.contrib.plugins.configrepo.groovy.export.IndentedStringWriter.newEntity(IndentedStringWriter.java:45)
2019-03-26T04:18:30.178415679Z 	at cd.go.contrib.plugins.configrepo.groovy.export.GroovyExporter.lambda$fullExport$1(GroovyExporter.java:51)
2019-03-26T04:18:30.178419764Z 	at cd.go.contrib.plugins.configrepo.groovy.export.IndentedStringWriter.withIndent(IndentedStringWriter.java:127)
2019-03-26T04:18:30.178423421Z 	at cd.go.contrib.plugins.configrepo.groovy.export.IndentedStringWriter.newEntity(IndentedStringWriter.java:51)
2019-03-26T04:18:30.178431834Z 	at cd.go.contrib.plugins.configrepo.groovy.export.IndentedStringWriter.newEntity(IndentedStringWriter.java:45)
2019-03-26T04:18:30.178435592Z 	at cd.go.contrib.plugins.configrepo.groovy.export.GroovyExporter.fullExport(GroovyExporter.java:50)
2019-03-26T04:18:30.178439187Z 	at cd.go.contrib.plugins.configrepo.groovy.executors.PipelineExportExecutor.exportedSource(PipelineExportExecutor.java:84)
2019-03-26T04:18:30.178442736Z 	... 148 common frames omitted
```

**Comment by chadlwilson** [comment]
This was fixed in 60ba8b74
